import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SolanaProviders from "@/components/SolanaProviders";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SolanaProviders>
        <Navbar />
        <body className={inter.className}>{children}</body>
      </SolanaProviders>
    </html>
  );
}
