import type { Method } from "@/lib/types";

export const METHODS: Method[] = [
  {
    id: "eth-block-number-base",
    name: "eth_blockNumber",
    description: "Get the latest block number on Base Sepolia",
    protocol: "JSON-RPC",
    network: "base-sepolia",
    networkDisplay: "Base Sepolia",
    rpcMethod: "eth_blockNumber",
    rpcParams: [],
  },
  {
    id: "eth-gas-price-base",
    name: "eth_gasPrice",
    description: "Get current gas price in wei on Base Sepolia",
    protocol: "JSON-RPC",
    network: "base-sepolia",
    networkDisplay: "Base Sepolia",
    rpcMethod: "eth_gasPrice",
    rpcParams: [],
  },
  {
    id: "eth-chain-id-ethereum",
    name: "eth_chainId",
    description: "Get chain ID for Ethereum mainnet",
    protocol: "JSON-RPC",
    network: "ethereum-mainnet",
    networkDisplay: "Ethereum",
    rpcMethod: "eth_chainId",
    rpcParams: [],
  },
  {
    id: "eth-block-number-arbitrum",
    name: "eth_blockNumber",
    description: "Get latest block number on Arbitrum One",
    protocol: "JSON-RPC",
    network: "arbitrum-mainnet",
    networkDisplay: "Arbitrum",
    rpcMethod: "eth_blockNumber",
    rpcParams: [],
  },
  {
    id: "eth-block-number-polygon",
    name: "eth_blockNumber",
    description: "Get latest block number on Polygon",
    protocol: "JSON-RPC",
    network: "matic-mainnet",
    networkDisplay: "Polygon",
    rpcMethod: "eth_blockNumber",
    rpcParams: [],
  },
  {
    id: "aptos-ledger-info",
    name: "Ledger Info",
    description: "Get Aptos ledger information",
    protocol: "REST",
    network: "aptos-mainnet",
    networkDisplay: "Aptos",
    restPath: "/v1/",
    restMethod: "GET",
  },
  {
    id: "aptos-block-height-1",
    name: "Block by Height",
    description: "Get Aptos block at height 1",
    protocol: "REST",
    network: "aptos-mainnet",
    networkDisplay: "Aptos",
    restPath: "/v1/blocks/by_height/1",
    restMethod: "GET",
  },
];
