import { type NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { main, appContainer, title, grid, cardTitle, cardDescription, link } from "../styles"

type CardProps = {
  name: string
  url: string
  description: string
}

function Card({ name, url, description }: CardProps) {
  return (
    <>
      <Link className={link} href={`${url}/`}>
        <h3 className={cardTitle}>{name}</h3>
        <div className={cardDescription}>{description}</div>
      </Link>
    </>
  )
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>QuickNode Portfolio App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={main}>
        <div className={appContainer}>
          <Link href="https://quicknode.com">
            <h1>QuickNode</h1>
            <h2 className={title}>Sample App</h2>
          </Link>

          <div className={grid}>
            <Card
              name="Fetch NFTs by Collection"
              url="/collections"
              description="View names, addresses, and images of NFTs in a given collection"
            />
            <Card
              name="Get Wallet Token Balance"
              url="/balance"
              description="View tokens, symbols, and balances in a given wallet"
            />
            <Card
              name="Fetch NFT Collection Details"
              url="/details"
              description="View NFT details including name, address, ERC token type, and genesis transaction"
            />
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
