{
 "title": "QuickNode Console API",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "QuickNode RPC Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(quicknode_rpc_requests)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QuickNode RPC Credits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(quicknode_rpc_credits)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QuickNode RPC Requests Total Last 30 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum_over_time(quicknode_rpc_requests[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QuickNode RPC Credits Total Last 30 days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum_over_time(quicknode_rpc_credits[30d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QuickNode Endpoint Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status, subdomain, label) (quicknode_rpc_response_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QuickNode Endpoint Response Time Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(label, subdomain, method, method) (quicknode_rpc_response_time_max)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}